-- List all unique cities where customers are located
select distinct customer_city
from customers
order by customer_city; 

-- Count the number of orders placed in 2017
select count(*) as orders_2017
from orders
where year(order_purchase_timestamp) = 2017;

-- Count the number of customers from each state
select customer_state, count(*) as customer_count
from customers
group by customer_state
order by customer_count desc; 

-- Revenue & sales analysis
-- Find the total sales per product category
select p.product_category_name, round(sum(oi.price + oi.freight_value), 2) as total_sales
from order_items as oi
join products p
on oi.product_id = p.product_id
group by p.product_category_name
order by total_sales desc;

-- Calculate the percentage of total revenue contributed by each category
select p.product_category_name,
round(sum(oi.price + oi.freight_value) * 100.0 / (select sum(price + freight_value) from order_items), 2) as revenue_percentage
from order_items as oi
join products p
on oi.product_id = p.product_id
group by p.product_category_name
order by revenue_percentage desc;

-- Calculate the percentage of orders paid in installments
select round(sum(case when payment_installments > 1 then 1 else 0 end) / count(*), 2) as installment_payment_percentage
from payments;

select round(sum(price + freight_value), 2) as total_revenue
from order_items;

-- Time-based & Trends analysis
-- Calculate the number of orders per month in 2018
select year(order_purchase_timestamp) as order_year,
month(order_purchase_timestamp) as order_month,
count(*) as total_orders
from orders
where year(order_purchase_timestamp) = 2018
group by 
year(order_purchase_timestamp),
month(order_purchase_timestamp)
order by order_month asc;

-- Calculate the cumulative sales per month for each year
with monthly_sales as (
	select 
    year(o.order_purchase_timestamp) as order_year,
    month(o.order_purchase_timestamp) as order_month,
    sum(oi.price + oi.freight_value) as monthly_revenue
    from orders o 
    join order_items oi
    on o.order_id = oi.order_id
    group by 
    year(o.order_purchase_timestamp),
    month(o.order_purchase_timestamp)
)
select order_year, order_month, monthly_revenue,
sum(monthly_revenue) over(partition by order_year order by order_month) as cumulative_revenue
from monthly_sales
order by order_year, order_month;

-- Calculate the year-over-year(yoy) growth rate of total sales
with yearly_sales as (
	select 
    year(o.order_purchase_timestamp) as order_year,
    sum(oi.price + oi.freight_value) as total_revenue
    from orders o 
    join order_items oi
    on o.order_id = oi.order_id
    group by year(o.order_purchase_timestamp)
)
select order_year, total_revenue,
round((total_revenue - LAG(total_revenue) over (order by order_year)) * 100.0 / 
LAG(total_revenue) over (order by order_year), 2) as yoy_growth_percentage
from yearly_sales
order by order_year;

-- Year wise orders
select year(order_purchase_timestamp) as year, count(*) as orders
from orders
group by year(order_purchase_timestamp)
order by year;

-- Customer Behavior analysis
-- Average number of products per order, grouped by customer city
select c.customer_city, round(count(oi.order_item_id) * 1.0 / count(distinct o.order_id), 2)
as avg_products_per_order
from order_items oi
join orders o
on oi.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
group by c.customer_city
order by avg_products_per_order desc;

-- Customer retention rate
-- % of customers who made another purchase within 6 months
with customer_orders as(
select
customer_id, min(order_purchase_timestamp) as first_order_date,
count(*) as total_orders
from orders
group by customer_id
)
select 
round(count(case when total_orders > 1 then 1 end) * 100.0 / count(*), 2)
as customer_retention_rate_percentage
from customer_orders;

--
select customer_id, count(*) as orders
from orders
group by customer_id
order by orders desc
limit 5;

-- Advanced Ranking & Insights
-- Total revenue generated by each seller and rank them by revenue
with seller_revenue as (
select
s.seller_id, round(sum(oi.price + oi.freight_value), 2) as total_revenue
from order_items oi
join sellers s
on oi.seller_id = s.seller_id
group by s.seller_id
)
select
seller_id, total_revenue, rank() over(order by total_revenue desc) as revenue_rank
from seller_revenue
order by revenue_rank;

-- Identify the top 3 customers who spent the most money in each year
with yearly_customer_spend as (
select
year(o.order_purchase_timestamp) as order_year,
o.customer_id,
round(sum(oi.price + oi.freight_value), 2) as total_spent
from orders o
join order_items oi
on o.order_id = oi.order_id
group by
year (o.order_purchase_timestamp),
o.customer_id
),
ranked_customers as (
select
order_year,
customer_id,
total_spent,
DENSE_RANK() over (
partition by order_year
order by total_spent desc
) as customer_rank
from yearly_customer_spend
)
select
order_year,
customer_id,
total_spent
from ranked_customers
where customer_rank <= 3
order by order_year, total_spent desc;

--
select seller_id, count(*) as items_sold
from order_items
group by seller_id
order by items_sold desc
limit 5;





